apiVersion: v2
name: jellyfin
description: Jellyfin Helm chart
type: application
version: 2.0.1
appVersion: 10.7.7
home: https://jellyfin.org
keywords:
  - jellyfin
  - media-server
  - streaming
  - tv
  - video
  - kodi
sources:
  - https://github.com/linuxserver/docker-jellyfin
  - https://github.com/alienth/helm-charts
maintainers:
  - name: Jason Harvey
    email: alienth@gmail.com
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - Complete rewrite
  artifacthub.io/images: |
    - name: linuxserver/jellyfin
      image: docker.io/linuxserver/jellyfin:10.7.7
