apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linuxgsm-sdtd.fullname" . }}
  labels:
    {{- include "linuxgsm-sdtd.labels" . | nindent 4 }}
data:
  {{- include "linuxgsm-sdtd.configData" . | nindent 2 }}
  sdtdserver.cfg: |
    startparameters="-quit -batchmode -nographics -dedicated -configfile=/serverconfig.xml"
