{{- if and .Values.persistence.serverFiles.enabled (not .Values.persistence.serverFiles.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "linuxgsm-sdtd.fullname" . }}-server-files
  labels:
    {{- include "linuxgsm-sdtd.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.persistence.serverFiles.accessMode | quote }}
  {{- with .Values.persistence.serverFiles.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.serverFiles.size | quote }}
{{- end }}
---
{{- if and .Values.persistence.saveData.enabled (not .Values.persistence.saveData.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "linuxgsm-sdtd.fullname" . }}-save-data
  labels:
    {{- include "linuxgsm-sdtd.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.persistence.saveData.accessMode | quote }}
  {{- with .Values.persistence.serverFiles.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.saveData.size | quote }}
{{- end }}
