apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linuxgsm-sdtd.fullname" . }}-serverconfig
  labels:
    {{- include "linuxgsm-sdtd.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets.xml: |
    <!-- Any lines in this secret will be added to serverconfig.xml. Primarily intended to be used for the server password. -->
    <!-- <property name="ServerPassword" value="example"/> -->
    {{- if .Values.serverConfig.ServerPassword }}
    <property name="ServerPassword" value="{{- .Values.serverConfig.ServerPassword }}"/>
    {{- end }}
    {{- if .Values.serverConfig.TelnetPassword }}
    <property name="TelnetPassword" value="{{- .Values.serverConfig.TelnetPassword }}"/>
    {{- end }}
