serverConfig:
  # Docs: https://7daystodie.fandom.com/wiki/Server:_serverconfig.xml

  ServerName: My Game Host
  ServerDescription: A 7 Days to Die server
  # 2 = public, 1 = friends-only, 0 = not listed
  ServerVisibility: 0
  ServerMaxPlayerCount: 8
  ServerReservedSlots: 0
  ServerAdminSlots: 0
  ServerAdminSlotsPermission: 0
  EACEnabled: true

  # To avoid setting these in values, instead edit the Secret this helm chart
  # will create and add these properties there.
  # See templates/secret.yaml
  # ServerPassword: ""
  # TelnetPassword: ""

  UserDataFolder: /save-data

  WebDashboardEnabled: false
  WebDashboardPort: 8080
  WebDashboardUrl: ""
  EnableMapRendering: false

  TelnetEnabled: true # required for LGSM to shut things down gracefully.
  TelnetPort: 8081
  TelnetFailedLoginLimit: 10

  GameName: My Game
  GameWorld: Navezgane
  GameMode: GameModeSurvival
  WorldGenSeed: asdf          # Only used if GameWorld is set to "RWG"
  WorldGenSize: 6144          # Only used if GameWorld is set to "RWG"

  GameDifficulty: 1
  BlockDamagePlayer: 100
  BlockDamageAI: 100
  BlockDamageAIBM: 100
  XPMultiplier: 100
  PlayerSafeZoneLevel: 5
  PlayerSafeZoneHours: 5

  EnemySpawnMode: true
  EnemyDifficulty: 0
  ZombieFeralSense: 0
  ZombieMove: 0
  ZombieMoveNight: 3
  ZombieFeralMove: 3
  ZombieBMMove: 3
  BloodMoonFrequency: 7
  BloodMoonRange: 0
  BloodMoonWarning: 8
  BloodMoonEnemyCount: 8

  LootAbundance: 100
  LootRespawnDays: 7
  AirDropFrequency: 72
  AirDropMarker: true

  LandClaimCount: 3
  LandClaimSize: 41
  LandClaimDeadZone: 30
  LandClaimExpiryTime: 7
  LandClaimDecayMode: 0
  LandClaimOnlineDurabilityModifier: 4
  LandClaimOfflineDurabilityModifier: 4
  LandClaimOfflineDelay: 0

  PartySharedKillRange: 100
  PlayerKillingMode: 3

  MaxSpawnedZombies: 64
  MaxSpawnedAnimals: 50
  ServerMaxAllowedViewDistance: 12
  MaxQueuedMeshLayers: 1000

  BuildCreate: false
  DayNightLength: 60
  DayLightLength: 18
  DropOnDeath: 1
  DropOnQuit: 1
  BedrollDeadZoneSize: 15
  BedrollExpiryTime: 45
  DynamicMeshEnabled: true
  DynamicMeshLandClaimOnly: true
  DynamicMeshLandClaimBuffer: 3
  DynamicMeshMaxItemCache: 3
  TwitchServerPermission: 90
  TwitchBloodMoonAllowed: false
  MaxChunkAge: -1
  SaveDataLimit: -1

serverInstall:
  branch: stable
  updateOnStart: false

image:
  registry: docker.io
  repository: gameservermanagers/gameserver
  tag: sdtd
  pullPolicy: IfNotPresent

podLabels: {}
podAnnotations: {}

persistence:
  # Where the server itself will install and be ran out of
  serverFiles:
    enabled: false
    storageClassName: ""
    existingClaim: ""
    accessMode: ReadWriteOnce
    # This should be at least 12Gi
    size: 15Gi

  # Where the save files from the server will be stored
  saveData:
    enabled: false
    storageClassName: ""
    existingClaim: ""
    accessMode: ReadWriteOnce
    size: 4Gi

  backup:
    enabled: false
    storageClassName: ""
    existingClaim: ""
    accessMode: ReadWriteOnce
    size: 4Gi

  additionalVolumes: {}

service:
  game:
    type: ClusterIP
    annotations: {}

  # requires serverConfig.WebDashboardEnabled
  dashboard:
    type: ClusterIP
    port: 8080
    annotations: {}

# Used for the web dashboard
ingress:
  enabled: false
  annotations: {}
  path: /
  pathType: Prefix
  ingressClassName: ""
  hosts:
    - chart-example.local


backup:
  enabled: false
  image:
    registry: docker.io
    repository: alienth/docker-backup-sdtd
    tag: latest
    pullPolicy: IfNotPresent
  # Be aware this is in UTC.
  schedule: "0 13 * * *" # https://en.wikipedia.org/wiki/Cron#Overview
